---
# Consult defaults/main.yml to learn about the role variables.
- block:
  - name: Start and enable the libvirt daemon
    systemd:
      name: libvirtd
      enabled: true
      state: started

# The only users that can access the all powerful `:///system` URI are root and any members of the libvirt group.
# Since good practice says to disable root login over SSH, remote usage of this URI requires adding a user to that group.
  - name: Enable user account access to libvirt daemon
    user:
      name: "{{ ansible_user_id }}"
      append: true
      groups: libvirt
  become: true
