---
- include_tasks: "libvirt_host_{{ ansible_distribution }}_tasks.yml"

- block:
  - name: Start and enable the libvirt service
    systemd:
      name: libvirtd
      enabled: true
      state: started

  - name: Delete default libvirt network
    virt_net:
      name: default
      state: absent
    when: libvirt_host_delete_default_network
# Can always be recreated with 'virsh net-define /usr/share/libvirt/networks/default.xml'

# The only users that can access the all powerful `:///system` URI are root and any members of the libvirt group.
# Since good practice says to disable root login over SSH, remote usage of this URI requires adding a user to that group.
  - name: Enable user account access to libvirt service
    user:
      name: "{{ item }}"
      append: true
      groups: libvirt
    with_items: "{{ libvirt_host_service_users }}"
  become: true
